<?xml version="1.0"?>
<robot name="bibi" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="gazebo.urdf.xacro"/>
  
  <!-- Define robot constants -->
  <xacro:property name="base_width" value="0.31"/>
  <xacro:property name="base_height" value="0.1"/>
  
  <xacro:property name="sphere_radius" value="0.4"/>
  <xacro:property name="wheel_ygap" value="0.145"/>
  <xacro:property name="wheel_radius" value="0.1"/>
  <xacro:property name="wheel_xoff" value="0.0"/>
  <xacro:property name="wheel_yoff" value="0.2"/>
  <xacro:property name="wheel_zoff" value="0.35"/>
  <xacro:property name="wheel_width" value="0.04"/>
  
  <xacro:property name="caster_xoff" value="0.14"/>

  <!-- Define inertia macros -->
  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${m}"/>
      <inertia ixx="${(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0" iyy="${(2/5) * m * (r*r)}" iyz="0.0" izz="${(2/5) * m * (r*r)}"/>
    </inertial>
  </xacro:macro>
  
  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0" iyy="${(m/12) * (3*r*r + h*h)}" iyz = "0" izz="${(m/2) * (r*r)}"/>
    </inertial>
  </xacro:macro>
  
  <link name="base_link">
    <visual>
      <geometry>
        <sphere radius="${sphere_radius}"/>
      </geometry>
      <material name="Yellow">
        <color rgba="1.0 1.0 0 1.0"/>
      </material>
    </visual>
    
    <collision>
      <origin xyz="0 0 0.055" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${sphere_radius + 0.08}"/>
      </geometry>
    </collision>

    <xacro:sphere_inertia m="20" r="${sphere_radius}"/>
  </link>
  
  <!-- Adding ring -->
  <link name="ring2">
    <visual>
      <geometry>
        <mesh filename="package://robot_bibi/details/Ring2.stl"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="Metallic">
        <color rgba="0.6 0.6 0.6 1.0"/>
        <specular rgba="0.5 0.5 0.5"/>
        <diffuse rgba="0.5 0.5 0.5 1.0"/>
        <shininess value="10.0"/>
      </material>
    </visual>
    
    <xacro:sphere_inertia m="0.001" r="${sphere_radius}"/>
  </link>
  
  <joint name="ring2_joint" type="fixed">
    <parent link="base_link" />
    <child link="ring2" />
    <origin xyz="0 0 ${-sphere_radius}" rpy="0 0 0" />
  </joint>


  <!-- Adding the half sphere -->
  <link name="half_sphere">
    <visual>
      <geometry>
        <mesh filename="package://robot_bibi/details/half.stl"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="Metallic1">
        <color rgba="0.4 0.4 0.4 1.0"/>
        <specular rgba="0.5 0.5 0.5"/>
        <diffuse rgba="0.1 0.1 0.1 1.0"/>
        <shininess value="10.0"/>
      </material>
    </visual>
 
    <xacro:sphere_inertia m="0.001" r="${sphere_radius}"/>
  </link>
  
  <joint name="half_sphere_joint" type="fixed">
    <parent link="base_link" />
    <child link="half_sphere" />
    <origin xyz="0 0 ${-sphere_radius}" rpy="0 0 0" />
  </joint>
  
  
  <!-- Adding ring -->
  <link name="ring1">
    <visual>
      <geometry>
        <mesh filename="package://robot_bibi/details/Ring1.stl"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="Metallic">
        <color rgba="0.6 0.6 0.6 1.0"/>
        <specular rgba="0.5 0.5 0.5"/>
        <diffuse rgba="0.5 0.5 0.5 1.0"/>
        <shininess value="10.0"/>
      </material>
    </visual>
    
    <xacro:sphere_inertia m="0.001" r="${sphere_radius}"/>
  </link>
  
  <joint name="ring1_joint" type="fixed">
    <parent link="base_link" />
    <child link="ring1" />
    <origin xyz="0 0 ${-sphere_radius}" rpy="0 0 0" />
  </joint>
  
  
  <!-- Adding hat -->
  <link name="hat_link">
    <visual>
      <geometry>
        <mesh filename="package://robot_bibi/details/hat.stl"/>
      </geometry>
      <origin xyz="0 0 ${sphere_radius}" rpy="0 0 0"/> 
      <material name="Metallic1">
        <color rgba="0.4 0.4 0.4 1.0"/>
        <specular rgba="0.5 0.5 0.5"/>
        <diffuse rgba="0.1 0.1 0.1 1.0"/>
        <shininess value="10.0"/>
       </material>
    </visual>
    
    <xacro:sphere_inertia m="0.001" r="${sphere_radius}"/>
  </link>
  
  <!-- Присоединение шапки к base_link -->
  <joint name="hat_joint" type="fixed">
      <parent link="base_link"/>
      <child link="hat_link"/>
      <origin xyz="0 0 ${sphere_radius}" rpy="0 0 0"/> 
  </joint>

  <!-- Robot Footprint -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0 0 -1" rpy="0 0 0"/>
  </joint>
  
  <!-- Wheels -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="Metallic">
          <color rgba="0.6 0.6 0.6 1.0"/>
          <specular rgba="0.5 0.5 0.5"/>
          <diffuse rgba="0.5 0.5 0.5 1.0"/>
          <shininess value="10.0"/>
        </material>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>

      <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}"/>
    </link>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect*wheel_xoff-0.2} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel prefix="drivewhl_l" x_reflect="-1" y_reflect="1" />
  <xacro:wheel prefix="drivewhl_r" x_reflect="-1" y_reflect="-1" />
  

  <!-- Caster Wheel -->
  <link name="front_caster">
    <visual>
      <origin xyz="0.045 0 -0.3" rpy="${pi/2} 0 0"/>
      <geometry>
        <sphere radius="${(wheel_radius)}"/>
      </geometry>
      <material name="Metallic1">
      </material>
    </visual>
    
    <collision>
      <origin xyz="0.045 0 -0.3" rpy="${pi/2} 0 0"/>
      <geometry>
        <sphere radius="${(wheel_radius)}"/>
      </geometry>
    </collision>

    <xacro:sphere_inertia m="0.01" r="${(wheel_radius)}"/>
    
  </link>

  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_caster"/>
    <origin xyz="${caster_xoff} 0.0 ${-(base_height/2)}" rpy="0 0 0"/>
  </joint>


  <gazebo reference="front_caster">
      <material>Gazebo/White</material>
      <mu1 value="0.001"/>
      <mu2 value="0.001"/>
  </gazebo>

</robot>

