<?xml version="1.0"?>
<robot name="bibi" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="gazebo.urdf.xacro"/>
  <!-- <xacro:include filename="lidar.urdf.xacro"/> -->
  <xacro:include filename="depth.urdf.xacro"/>
  
  
  <!-- Define robot constants -->
  <xacro:property name="base_width" value="0.31"/>
  <xacro:property name="base_height" value="0.1"/>
  
  <xacro:property name="sphere_radius" value="0.4"/>
  <xacro:property name="wheel_ygap" value="0.14"/>
  <xacro:property name="wheel_radius" value="0.1"/>
  <xacro:property name="wheel_xoff" value="0.0"/>
  <xacro:property name="wheel_yoff" value="0.2"/>
  <xacro:property name="wheel_zoff" value="0.35"/>
  <xacro:property name="wheel_width" value="0.04"/>
  
  <xacro:property name="caster_xoff" value="0.14"/>
  
  <xacro:property name="Eye_ygap" value="-0.04"/>
  <xacro:property name="Eye_radius" value="0.1"/>
  <xacro:property name="Eye_xoff" value="0.37"/>
  <xacro:property name="Eye_zoff" value="-0.09"/>
  <xacro:property name="Eye_width" value="0.001"/>
  
  <xacro:property name="Pupil_xoff" value="0.38"/>
  <xacro:property name="Pupil_zoff" value="-0.09"/>
  <xacro:property name="Pupil_ygap" value="-0.06"/>
  
  <xacro:property name="Pup_xoff" value="0.39"/>
  <xacro:property name="Pup_zoff" value="-0.09"/>
  <xacro:property name="Pup_ygap" value="-0.07"/>
  
  <xacro:property name="Es_xoff" value="0.375"/>
  <xacro:property name="Es_zoff" value="-0.09"/>
  <xacro:property name="Es_ygap" value="-0.05"/>
  
  <xacro:property name="Ear_xoff" value="0.05"/>
  <xacro:property name="Ear_zoff" value="-0.41"/>
  <xacro:property name="Ear_ygap" value="0.08"/>
  

  <!-- Define inertia macros -->
  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${m}"/>
      <inertia ixx="${(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0" iyy="${(2/5) * m * (r*r)}" iyz="0.0" izz="${(2/5) * m * (r*r)}"/>
    </inertial>
  </xacro:macro>
  
  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0" iyy="${(m/12) * (3*r*r + h*h)}" iyz = "0" izz="${(m/2) * (r*r)}"/>
    </inertial>
  </xacro:macro>
  
  
  
  <link name="base_link">
    <visual>
      <geometry>
        <sphere radius="${sphere_radius}"/>
      </geometry>
      <material name="Yellow">
        <color rgba="1.0 1.0 0 1.0"/>
      </material>
    </visual>
    
    <collision>
      <origin xyz="0 0 0.055" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${sphere_radius + 0.08}"/>
      </geometry>
    </collision>

    <xacro:sphere_inertia m="20" r="${sphere_radius}"/>
  </link>
  
  
  <!-- Adding ring -->
  <link name="ring2">
    <visual>
      <geometry>
        <mesh filename="file://$(find robot_bibi)/details/Ring2.stl"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="Metallic">
        <color rgba="0.5 0.5 0.5 1.0"/>
        <specular rgba="0.5 0.5 0.5"/>
        <diffuse rgba="0.2 0.2 0.2 1.0"/>
        <shininess value="10.0"/>
      </material>
    </visual>
    
    <xacro:sphere_inertia m="0.001" r="${sphere_radius}"/>
  </link>
  
  <joint name="ring2_joint" type="fixed">
    <parent link="base_link" />
    <child link="ring2" />
    <origin xyz="0 0 ${-sphere_radius}" rpy="0 0 0" />
  </joint>


  <!-- Adding the half sphere -->
  <link name="half_sphere">
    <visual>
      <geometry>
        <mesh filename="file://$(find robot_bibi)/details/half.stl"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="Metallic1">
        <color rgba="0.4 0.4 0.4 1.0"/>
        <specular rgba="0.5 0.5 0.5"/>
        <diffuse rgba="0.1 0.1 0.1 1.0"/>
        <shininess value="10.0"/>
      </material>
    </visual>
 
    <xacro:sphere_inertia m="0.001" r="${sphere_radius}"/>
  </link>
  
  <joint name="half_sphere_joint" type="fixed">
    <parent link="base_link" />
    <child link="half_sphere" />
    <origin xyz="0 0 ${-sphere_radius}" rpy="0 0 0" />
  </joint>
  
  
  <!-- Adding ring1 -->
  <link name="ring1">
    <visual>
      <geometry>
        <mesh filename="file://$(find robot_bibi)/details/Ring1.stl"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="Metallic">
        <color rgba="0.5 0.5 0.5 1.0"/>
        <specular rgba="0.5 0.5 0.5"/>
        <diffuse rgba="0.2 0.2 0.2 1.0"/>
        <shininess value="10.0"/>
      </material>
    </visual>
    
    <xacro:sphere_inertia m="0.001" r="${sphere_radius}"/>
  </link>
  
  <joint name="ring1_joint" type="fixed">
    <parent link="base_link" />
    <child link="ring1" />
    <origin xyz="0 0 ${-sphere_radius}" rpy="0 0 0" />
  </joint>
  
  
  <!-- Adding hat -->
  <link name="hat_link">
    <visual>
      <geometry>
        <mesh filename="file://$(find robot_bibi)/details/hat.stl"/>
      </geometry>
      <origin xyz="0 0 ${sphere_radius}" rpy="0 0 0"/> 
      <material name="Metallic1">
        <color rgba="0.4 0.4 0.4 1.0"/>
        <specular rgba="0.5 0.5 0.5"/>
        <diffuse rgba="0.1 0.1 0.1 1.0"/>
        <shininess value="10.0"/>
       </material>
    </visual>
    
    <xacro:sphere_inertia m="0.001" r="${sphere_radius}"/>
  </link>
  
  <joint name="hat_joint" type="fixed">
      <parent link="base_link"/>
      <child link="hat_link"/>
      <origin xyz="0 0 ${sphere_radius}" rpy="0 0 0"/> 
  </joint>


  <!-- Robot Footprint -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0 0 -1" rpy="0 0 0"/>
  </joint>
  
  
  <!-- Eye1 -->
  <link name="Eye_l_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${Eye_radius}" length="${Eye_width}"/>
      </geometry>
      <material name="White">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </visual>
 
    <xacro:cylinder_inertia m="0.001" r="${Eye_radius}" h="${Eye_width}"/>
  </link>

  <joint name="Eye_l_joint" type="fixed">
    <parent link="base_link"/>
    <child link="Eye_l_link"/>
    <origin xyz="${-1*Eye_xoff} ${1*(base_width/2+Eye_ygap)} ${-Eye_zoff}" rpy="0.23 0 1.3"/>
    <axis xyz="0 1 0"/>
  </joint>

  
  <!-- Eye2 -->
  <link name="Eye_r_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${Eye_radius}" length="${Eye_width}"/>
      </geometry>
      <material name="White">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </visual>
      
    <xacro:cylinder_inertia m="0.001" r="${Eye_radius}" h="${Eye_width}"/>
  </link>

  <joint name="Eye_r_joint" type="fixed">
    <parent link="base_link"/>
    <child link="Eye_r_link"/>
    <origin xyz="${-1*Eye_xoff} ${-1*(base_width/2+Eye_ygap)} ${-Eye_zoff}" rpy="0.23 0 1.87"/>
    <axis xyz="0 1 0"/>
  </joint>
  
  
  <!-- Es1 -->
  <link name="Es_l_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="0.07" length="0.001"/>
      </geometry>
      <material name="Grind">
        <color rgba="0.0 0.5 0.0 1.0"/>
      </material>
    </visual>

    <xacro:cylinder_inertia m="0.001" r="0.07" h="0.001"/>
  </link>

  <joint name="Es_l_joint" type="fixed">
    <parent link="base_link"/>
    <child link="Es_l_link"/>
    <origin xyz="${-1*Es_xoff} ${1*(base_width/2+Es_ygap)} ${-Es_zoff}" rpy="0.23 0 1.3"/>
    <axis xyz="0 1 0"/>
  </joint>

  
  <!-- Es2 -->
  <link name="Es_r_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="0.07" length="0.001"/>
      </geometry>
      <material name="Grind">
        <color rgba="0.0 0.5 0.0 1.0"/>
      </material>
    </visual>
    
    <xacro:cylinder_inertia m="0.001" r="0.07" h="0.001"/>
  </link>

  <joint name="Es_r_joint" type="fixed">
    <parent link="base_link"/>
    <child link="Es_r_link"/>
    <origin xyz="${-1*Es_xoff} ${-1*(base_width/2+Es_ygap)} ${-Es_zoff}" rpy="0.23 0 1.87"/>
    <axis xyz="0 1 0"/>
  </joint>
  
  
  <!-- Pupils1 -->
  <link name="Pupil_l_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.001"/>
      </geometry>
      <material name="Grin">
        <color rgba="0.8 1.0 0.8 1.0"/>
      </material>
    </visual>

    <xacro:cylinder_inertia m="0.001" r="0.05" h="0.001"/>
  </link>

  <joint name="Pupil_l_joint" type="fixed">
    <parent link="base_link"/>
    <child link="Pupil_l_link"/>
    <origin xyz="${-1*Pupil_xoff} ${1*(base_width/2+Pupil_ygap)} ${-Pupil_zoff}" rpy="0.23 0 1.3"/>
    <axis xyz="0 1 0"/>
  </joint>

  
  <!-- Pupils2 -->
  <link name="Pupil_r_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.001"/>
      </geometry>
      <material name="Grin">
        <color rgba="0.8 1.0 0.8 1.0"/>
      </material>
    </visual>

    <xacro:cylinder_inertia m="0.001" r="0.05" h="0.001"/>
  </link>

  <joint name="Pupil_r_joint" type="fixed">
    <parent link="base_link"/>
    <child link="Pupil_r_link"/>
    <origin xyz="${-1*Pupil_xoff} ${-1*(base_width/2+Pupil_ygap)} ${-Pupil_zoff}" rpy="0.23 0 1.87"/>
    <axis xyz="0 1 0"/>
  </joint>
  
  
  <!-- Pup1 -->
  <link name="Pup_l_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="0.028" length="0.001"/>
      </geometry>
      <material name="Black">
        <color rgba="0.0 0.0 0.0 1.0"/>
      </material>
    </visual>

    <xacro:cylinder_inertia m="0.001" r="0.028" h="0.001"/>
  </link>

  <joint name="Pup_l_joint" type="fixed">
    <parent link="base_link"/>
    <child link="Pup_l_link"/>
    <origin xyz="${-1*Pup_xoff} ${1*(base_width/2+Pup_ygap)} ${-Pup_zoff}" rpy="0.23 0 1.3"/>
    <axis xyz="0 1 0"/>
  </joint>

  
  <!-- Pup2 -->
  <link name="Pup_r_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="0.028" length="0.001"/>
      </geometry>
      <material name="Black">
        <color rgba="0.0 0.0 0.0 1.0"/>
      </material>
    </visual>

    <xacro:cylinder_inertia m="0.001" r="0.028" h="0.001"/>
  </link>

  <joint name="Pup_r_joint" type="fixed">
    <parent link="base_link"/>
    <child link="Pup_r_link"/>
    <origin xyz="${-1*Pup_xoff} ${-1*(base_width/2+Pup_ygap)} ${-Pup_zoff}" rpy="0.23 0 1.87"/>
    <axis xyz="0 1 0"/>
  </joint>
  
  
  <!-- Ear1 -->
  <link name="Ear_r_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.025"/>
      </geometry>
      <material name="Greeen">
        <color rgba="0.0 1.0 0.0 1.0"/>
      </material>
    </visual>

    <xacro:cylinder_inertia m="0.001" r="0.05" h="0.025"/>
  </link>

  <joint name="Ear_r_joint" type="fixed">
    <parent link="base_link"/>
    <child link="Ear_r_link"/>
    <origin xyz="${-1*Ear_xoff} ${-1*(base_width/2+Ear_ygap)} ${-Ear_zoff}" rpy="2.15 0.0 0.0"/>
    <axis xyz="0 1 0"/>
  </joint>
  
  
  <!-- Ear2 -->
  <link name="Ear_l_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.025"/>
      </geometry>
      <material name="Red">
        <color rgba="1.0 0.0 0.0 1.0"/>
      </material>
    </visual>

    <xacro:cylinder_inertia m="0.001" r="0.05" h="0.025"/>
  </link>

  <joint name="Ear_l_joint" type="fixed">
    <parent link="base_link"/>
    <child link="Ear_l_link"/>
    <origin xyz="${-1*Ear_xoff} ${1*(base_width/2+Ear_ygap)} ${-Ear_zoff}" rpy="0.95 0 0.0"/>
    <axis xyz="0 1 0"/>
  </joint>
  
  
  <!-- Bolt1 -->
  <link name="Bolt_h_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="0.029" length="0.02"/>
      </geometry>
      <material name="Metallic1">
      </material>
    </visual>

    <xacro:cylinder_inertia m="0.001" r="0.029" h="0.02"/>
  </link>

  <joint name="Bolt_h_joint" type="fixed">
    <parent link="base_link"/>
    <child link="Bolt_h_link"/>
    <origin xyz="${-1*(0.42)} ${-1*(base_width/2+(-0.15))} ${-(-0.21)}" rpy="0.3 0 1.6"/>
    <axis xyz="0 1 0"/>
  </joint>
  
  
  <!-- Bolt1.1 -->
  <link name="Bolt_hl_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="0.029" length="0.02"/>
      </geometry>
      <material name="Metallic1">
      </material>
    </visual>

    <xacro:cylinder_inertia m="0.001" r="0.029" h="0.02"/>
  </link>

  <joint name="Bolt_hl_joint" type="fixed">
    <parent link="base_link"/>
    <child link="Bolt_hl_link"/>
    <origin xyz="${-1*(0.23)} ${-1*(base_width/2+(-0.518))} ${-(-0.166)}" rpy="0.3 0 0.5"/>
    <axis xyz="0 1 0"/>
  </joint>
  
  
  <!-- Bolt1.2 -->
  <link name="Bolt_hr_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="0.029" length="0.02"/>
      </geometry>
      <material name="Metallic1">
      </material>
    </visual>

    <xacro:cylinder_inertia m="0.001" r="0.029" h="0.02"/>
  </link>

  <joint name="Bolt_hr_joint" type="fixed">
    <parent link="base_link"/>
    <child link="Bolt_hr_link"/>
    <origin xyz="${-1*(0.23)} ${-1*(base_width/2+(0.228))} ${-(-0.156)}" rpy="0.3 0 2.55"/>
    <axis xyz="0 1 0"/>
  </joint>
  
  
  <!-- Bolt2 -->
  <link name="Bolt_b_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="0.029" length="0.02"/>
      </geometry>
      <material name="Metallic1">
      </material>
    </visual>

    <xacro:cylinder_inertia m="0.001" r="0.029" h="0.02"/>
  </link>

  <joint name="Bolt_b_joint" type="fixed">
    <parent link="base_link"/>
    <child link="Bolt_b_link"/>
    <origin xyz="${-1*(0.458)} ${-1*(base_width/2+(-0.154))} ${-(0.022)}" rpy="-0.1 0 1.57"/>
    <axis xyz="0 1 0"/>
  </joint>
  
  
  <!-- Bolt2.1 -->
  <link name="Bolt_bl_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="0.029" length="0.02"/>
      </geometry>
      <material name="Metallic1">
      </material>
    </visual>

    <xacro:cylinder_inertia m="0.001" r="0.029" h="0.02"/>
  </link>

  <joint name="Bolt_bl_joint" type="fixed">
    <parent link="base_link"/>
    <child link="Bolt_bl_link"/>
    <origin xyz="${-1*(0.26)} ${-1*(base_width/2+(-0.525))} ${-(0.01)}" rpy="-0.1 0 0.6"/>
    <axis xyz="0 1 0"/>
  </joint>
  
  
  <!-- Bolt2.2 -->
  <link name="Bolt_br_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="0.029" length="0.02"/>
      </geometry>
      <material name="Metallic1">
      </material>
    </visual>

    <xacro:cylinder_inertia m="0.001" r="0.029" h="0.02"/>
  </link>

  <joint name="Bolt_br_joint" type="fixed">
    <parent link="base_link"/>
    <child link="Bolt_br_link"/>
    <origin xyz="${-1*(0.23)} ${-1*(base_width/2+(0.22))} ${-(0.04)}" rpy="-0.1 0 2.66"/>
    <axis xyz="0 1 0"/>
  </joint>
  
  
  <!-- Wheels -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="Metallic">
          <color rgba="0.6 0.6 0.6 1.0"/>
          <specular rgba="0.5 0.5 0.5"/>
          <diffuse rgba="0.5 0.5 0.5 1.0"/>
          <shininess value="10.0"/>
        </material>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>

      <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}"/>
    </link>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect*wheel_xoff-0.2} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel prefix="drivewhl_l" x_reflect="-1" y_reflect="1" />
  <xacro:wheel prefix="drivewhl_r" x_reflect="-1" y_reflect="-1" />
  

  <!-- Caster Wheel -->
  <link name="front_caster">
    <visual>
      <origin xyz="0.045 0 -0.3" rpy="${pi/2} 0 0"/>
      <geometry>
        <sphere radius="${(wheel_radius)}"/>
      </geometry>
      <material name="Metallic1">
      </material>
    </visual>
    
    <collision>
      <origin xyz="0.045 0 -0.3" rpy="${pi/2} 0 0"/>
      <geometry>
        <sphere radius="${(wheel_radius)}"/>
      </geometry>
    </collision>

    <xacro:sphere_inertia m="0.01" r="${(wheel_radius)}"/>
    
  </link>

  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_caster"/>
    <origin xyz="${caster_xoff} 0.0 ${-(base_height/2)}" rpy="0 0 0"/>
  </joint>


  <gazebo reference="front_caster">
      <material>Gazebo/White</material>
      <mu1 value="0.001"/>
      <mu2 value="0.001"/>
  </gazebo>

</robot>

